Fix Bug where Placeholder is wider than Main image
MatteoGabriele/vue-progressive-image pull request #13
Opened 2017-08-02 07:02 UTC by dmattia

The `.progressive-image-placeholder` should have the same size as the `.progressive-image-main` class so that the main image blends nicely on top of the placeholder image.  This bug occurs when the main image is not wide enough to fill its parent container

2017-08-02 21:38 UTC, MatteoGabriele commented on src/component/image.vue
> +    height: auto;
with `height` set to `auto` there's no placeholder at all because the height will be 0. 
the `height` needs to be 100%

![screen recording 2017-08-02 at 11 31 pm](https://user-images.githubusercontent.com/5337152/28895972-cc2ea4a2-77da-11e7-8c63-82f5f36a918b.gif)

2017-08-02 21:39 UTC, MatteoGabriele requested changes
please check my comment in the code. thanks

2017-08-03 18:07 UTC, dmattia commented
I changed back the placeholder height.  Is there any way you could add your example code into this github repo, either in master or in the dev branch? It would make it easier to test changes from the outside.

2017-08-03 21:42 UTC, MatteoGabriele commented
Sure it is something that I want to add asap. I've just created a new issue for this https://github.com/MatteoGabriele/vue-progressive-image/issues/14

For what concerns this PR, the code is already like this on master 

https://github.com/MatteoGabriele/vue-progressive-image/blob/master/src/component/image.vue#L95-L96

soI will close this PR.

Thanks for your time!

2017-08-04 05:03 UTC, dmattia commented
The important change in the code was to the class `progressive-image-main`. The placeholder always filled the full space (width: 100%). The main image does not if the image is not as wide as the parent div.

2017-08-04 05:26 UTC, MatteoGabriele commented
Ah! Ahhaahahh sorry man. didn't read it correctly 😂

2017-08-04 06:03 UTC, merged